# One classifier each name: OCEN (Name group)
This method throw away the record below threshold.

Also this file evaluate different embedding method with OCEN.
1. Text embedding only
2. Citation embedding only
3. Combined embedding

In [1]:
import os
import sys
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

import com_func

# parameters
#----- threshold for selecting set of name group -----------#
threshold_select_name_group = 100
#----- threshold for selecting min sample in name group ----#
threshold_min_class_sample_size = 100

Dataset = "pubmed"

In [2]:
# text embedding only
pp_text_emb = ["tf", "tf_idf", "lsa", "pv_dm", "pv_dbow"]
pp_citation_emb = ["off"]

In [5]:
# citation embedding only
pp_text_emb = ["off"]
pp_citation_emb = ["node2vec", "n2v"]

In [2]:
# combined embedding
pp_text_emb = ["lsa", "pv_dm", "pv_dbow"]
pp_citation_emb = ["n2v"]

In [4]:
print(pp_text_emb)
print(pp_citation_emb)

['tf', 'tf_idf', 'lsa', 'pv_dm', 'pv_dbow']
['off']


In [5]:
import io
import collections
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from statistics import mean 

# fix random seed for reproducibility
np.random.seed(1)

fileDir = "../Data/"+Dataset+"/canopies_labeled/"
listfiles = os.listdir(fileDir)

lr_diff_embedding_result = []
svm_diff_embedding_result = []

# ----------------------- different textual embedding ----------------------#
for text_emb in pp_text_emb:
    print("Load text embedding: ", text_emb)
    # read pretrained embeddings
    all_textual_embedding, all_textual_emb_pid = com_func.read_text_embedding(emb_type=text_emb, training_size="140k")
    
    for citation_emb in pp_citation_emb:
        print("Load citation embedding: ", citation_emb)
        all_citation_embedding = com_func.read_citation_embedding_sorted(emb_type = citation_emb)
        all_citation_emb_pid = [emb[0] for emb in all_citation_embedding]
        all_citation_embedding = [emb[1:] for emb in all_citation_embedding]
        
        # collect statistic to output
        allname, num_class, per_class_count, selected_sample_size, orginal_sample_size= ([] for i in range(5))
        all_mnb_accuracy, all_mnb_f1 = ([] for i in range(2))
        all_LR_accuracy, all_LR_f1 = ([] for i in range(2))
        all_svcLinear_accuracy, all_svcLinear_f1 = ([] for i in range(2))

        total_selected_group = 0

        # ------- different name group in all name group --------------------#
        for file in listfiles:
            # group name
            temp = file.split("_")
            name = temp[1]+"_"+temp[-1]
            print("For name: ",name)
            # read needed content in labeled file
            labeled_data = com_func.read_pid_aid(fileDir+file)
            #----------- select name group contain productive author------------------------------------#
            #----------- (contain pair of author write more than 100 papers) ---------------------------#
            # count number of paper each author write based on author ID
            authorCounter = collections.Counter(labeled_data["authorID"])
            # remove name group that do not contain pair of author write more than 100 papers
            for k in list(authorCounter):
                if authorCounter[k] < threshold_select_name_group:
                    del authorCounter[k]
            # if only have one class or no class pass the threshold, not applicable
            if(len(authorCounter)==0) or (len(authorCounter)==1):
                print(name, " pass")
            else:
                total_selected_group+= 1
                orginal_sample_size.append(len(labeled_data))
                #--------select authors in name group are very productive (more than threshold)---------#
                print("Total sample size before apply threshold: ",len(labeled_data))
                # count number of paper each author write based on author ID
                paperCounter = collections.Counter(labeled_data["authorID"])
                print(paperCounter)
                print("Total author before apply threshoid: ", len(paperCounter))
                # collect per class statistic
                for k in list(paperCounter):
                    if paperCounter[k] < threshold_min_class_sample_size:
                        del paperCounter[k]
                temp =list(paperCounter.keys())
                print(temp)
                print("Total author after apply threshoid: ", len(temp))
                # remove samples that are smaller than threshold
                labeled_data = labeled_data[labeled_data.authorID.isin(temp)]
                print("Total sample size after apply threshold: ",len(labeled_data))
                selected_sample_size.append(len(labeled_data))
                allname.append(name)
                num_class.append(len(paperCounter))
                per_class_count.append(paperCounter)
                #------------ extract paper representation -------------------------------------------#
                # shuffle the data
                labeled_data = labeled_data.sample(frac=1).reset_index(drop=True)
                # extract true label and pid
                label = labeled_data["authorID"]
                pid = labeled_data["paperID"]
                # list of different data field
                part_collection = []
                # select feature wanted to fit to clustering/classification algorithm
                # data part, textual information
                data_part_textual = com_func.extract_embedding(all_textual_embedding, all_textual_emb_pid, pid)
                print("Text embedding shape: ", data_part_textual.shape)
                part_collection.append(data_part_textual)
                # data part, citation information
                data_part_citation = com_func.extract_embedding(all_citation_embedding, all_citation_emb_pid, pid)
                print("Citation embedding shape: ", data_part_citation.shape)
                part_collection.append(data_part_citation)
                # merge different part of data data together by concatenate it all together
                # remove empty emb (when emb set off)
                part_collection = [part for part in part_collection if len(part)!=0]
                if len(part_collection)>1:
                    combinedata = np.concatenate(part_collection,axis=1)
                elif len(part_collection)==1:
                    if isinstance(part_collection[0], pd.DataFrame):
                        combinedata = part_collection[0].values
                    else:
                        combinedata = part_collection[0]
                else:
                    print("No data available")
                    break
                print("Final feature (combined embedding) shape: ", combinedata.shape)
                # -------------- using converted feature vector to train classifier-------------------#
                if text_emb == "tf":
                    # using multinomial naive bayes
                    clf = MultinomialNB()
                    mnbaccuracy, mnbmarcof1, tp, tn, fp, fn = com_func.k_fold_cv_with_accumulate_statistic(combinedata, label, clf, k=10)
                    print("MNB Accuracy: ",mnbaccuracy)
                    print("MNB F1: ", mnbmarcof1)
                    all_mnb_accuracy.append(mnbaccuracy)
                    all_mnb_f1.append(mnbmarcof1)
                # using logistic regression
                clf = LogisticRegression(multi_class='ovr')
                LRaccuracy, LRmarcof1, tp, tn, fp, fn = com_func.k_fold_cv_with_accumulate_statistic(combinedata, label, clf, k=10)
                print("LR Accuracy: ",LRaccuracy)
                print("LR F1: ", LRmarcof1)
                all_LR_accuracy.append(LRaccuracy)
                all_LR_f1.append(LRmarcof1)
                # using SVM with linear kernal
                clf = SVC(decision_function_shape='ovr', kernel='linear')
                svcaccuracy, svcmarcof1, tp, tn, fp, fn = com_func.k_fold_cv_with_accumulate_statistic(combinedata, label, clf, k=10)
                print("svc Accuracy: ",svcaccuracy)
                print("svc F1: ", svcmarcof1)
                all_svcLinear_accuracy.append(svcaccuracy)
                all_svcLinear_f1.append(svcmarcof1)

        if text_emb == "tf":
            # write evaluation result to excel
            output = pd.DataFrame({'Name Group':allname,"Class number":num_class,"Per class size":per_class_count, 
                                   "Total selected sample size":selected_sample_size,"Orginal sample size":orginal_sample_size,
                                   "MNB Accuracy":all_mnb_accuracy, "MNB macro F1": all_mnb_f1, 
                                   "svc(linear) accuracy":all_svcLinear_accuracy, "svc(linear) macro f1": all_svcLinear_f1, 
                                   "logistic regression accuracy":all_LR_accuracy, "logistic regression macro f1": all_LR_f1})
        else:
            # write evaluation result to excel
            output = pd.DataFrame({'Name Group':allname, "Class number":num_class, "Per class size":per_class_count,
                                   "Total selected sample size":selected_sample_size,"Orginal sample size":orginal_sample_size,
                                   "svc(linear) accuracy":all_svcLinear_accuracy, "svc(linear) macro f1": all_svcLinear_f1, 
                                   "logistic regression accuracy":all_LR_accuracy, "logistic regression macro f1": all_LR_f1})

        savePath = "../../result/"+Dataset+"/OCEN_sample=140k/"
        filename = "citation="+citation_emb+"_textual="+text_emb+"_threshold="+str(threshold_min_class_sample_size)+".csv"
        com_func.write_csv_df(savePath, filename, output)
        print("Done")

        lr_diff_embedding_result.append(all_LR_f1)
        svm_diff_embedding_result.append(all_svcLinear_f1)

Load text embedding:  tf
Total text vector records: 135796
Vector dimension:  50000
Load citation embedding:  off
For name:  j_read
j_read  pass
For name:  f_esteves
f_esteves  pass
For name:  c_miller
c_miller  pass
For name:  r_jha
r_jha  pass
For name:  a_lowe
a_lowe  pass
For name:  a_vega
a_vega  pass
For name:  k_smith
k_smith  pass
For name:  j_gordon
j_gordon  pass
For name:  s_liao
s_liao  pass
For name:  j_qian
j_qian  pass
For name:  s_bernardi
s_bernardi  pass
For name:  t_hill
t_hill  pass
For name:  s_schindler
s_schindler  pass
For name:  j_williams
j_williams  pass
For name:  s_jacobson
s_jacobson  pass
For name:  e_andrade
e_andrade  pass
For name:  t_santos
t_santos  pass
For name:  k_kim
Total sample size before apply threshold:  1111
Counter({'0000-0002-6929-5359': 211, '0000-0001-9498-284X': 154, '0000-0002-5878-8895': 139, '0000-0002-1864-3392': 92, '0000-0002-7045-8004': 57, '0000-0001-7896-6751': 57, '0000-0002-7991-9428': 55, '0000-0002-4010-1063': 45, '0000-00

a_nielsen  pass
For name:  j_conde
j_conde  pass
For name:  k_wright
k_wright  pass
For name:  m_parker
m_parker  pass
For name:  h_huang
h_huang  pass
For name:  j_terry
j_terry  pass
For name:  y_xu
y_xu  pass
For name:  a_melo
a_melo  pass
For name:  r_doyle
r_doyle  pass
For name:  m_bernardo
m_bernardo  pass
For name:  j_soares
j_soares  pass
For name:  j_richard
j_richard  pass
For name:  p_robinson
Total sample size before apply threshold:  275
Counter({'0000-0002-7878-0313': 133, '0000-0002-0736-9199': 119, '0000-0002-3156-3418': 19, '0000-0002-0577-3147': 4})
Total author before apply threshoid:  4
['0000-0002-0736-9199', '0000-0002-7878-0313']
Total author after apply threshoid:  2
Total sample size after apply threshold:  252
Total missing sample:  0
Text embedding shape:  (252, 50000)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (252, 50000)
Binary case
                     precision    recall  f1-score   support

000

c_nogueira  pass
For name:  j_cooper
j_cooper  pass
For name:  k_lau
k_lau  pass
For name:  s_hussein
s_hussein  pass
For name:  z_luo
z_luo  pass
For name:  c_pimentel
c_pimentel  pass
For name:  s_ito
s_ito  pass
For name:  f_zhang
f_zhang  pass
For name:  s_chapman
s_chapman  pass
For name:  j_rosa
j_rosa  pass
For name:  y_yin
y_yin  pass
For name:  p_tavares
p_tavares  pass
For name:  a_palma
a_palma  pass
For name:  e_shaw
e_shaw  pass
For name:  m_cameron
m_cameron  pass
For name:  a_reid
a_reid  pass
For name:  d_gil
d_gil  pass
For name:  s_morgan
s_morgan  pass
For name:  p_ross
p_ross  pass
For name:  l_simon
l_simon  pass
For name:  k_thomas
k_thomas  pass
For name:  l_torres
l_torres  pass
For name:  p_ding
p_ding  pass
For name:  g_morris
g_morris  pass
For name:  s_andrews
s_andrews  pass
For name:  b_yan
b_yan  pass
For name:  r_hu
r_hu  pass
For name:  j_braun
j_braun  pass
For name:  c_he
c_he  pass
For name:  w_lu
w_lu  pass
For name:  r_radhakrishnan
r_radhakrishnan

Total missing sample:  0
Text embedding shape:  (208, 50000)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (208, 50000)
Binary case
                     precision    recall  f1-score   support

0000-0001-5833-989X       0.95      0.99      0.97       100
0000-0003-3171-7672       0.99      0.95      0.97       108

           accuracy                           0.97       208
          macro avg       0.97      0.97      0.97       208
       weighted avg       0.97      0.97      0.97       208

TP:  103 TN:  99 FP:  1 FN:  5
MNB Accuracy:  0.9711538461538461
MNB F1:  0.9711431742508324
Binary case
                     precision    recall  f1-score   support

0000-0001-5833-989X       1.00      0.98      0.99       100
0000-0003-3171-7672       0.98      1.00      0.99       108

           accuracy                           0.99       208
          macro avg       0.99      0.99      0.99       208
       weighted avg       0.99 

Binary case
                     precision    recall  f1-score   support

0000-0002-6391-1341       1.00      0.95      0.97       112
0000-0002-6794-6656       0.97      1.00      0.98       180

           accuracy                           0.98       292
          macro avg       0.98      0.97      0.98       292
       weighted avg       0.98      0.98      0.98       292

TP:  180 TN:  106 FP:  6 FN:  0
svc Accuracy:  0.9794520547945206
svc F1:  0.9780418107986163
For name:  r_sinha
r_sinha  pass
For name:  c_turner
c_turner  pass
For name:  y_su
y_su  pass
For name:  a_popov
a_popov  pass
For name:  w_liao
w_liao  pass
For name:  j_zhong
j_zhong  pass
For name:  a_wheeler
a_wheeler  pass
For name:  m_walsh
m_walsh  pass
For name:  r_figueiredo
r_figueiredo  pass
For name:  y_lin
Total sample size before apply threshold:  785
Counter({'0000-0003-3791-7587': 146, '0000-0001-8153-1441': 115, '0000-0003-1224-6561': 64, '0000-0002-4192-3165': 49, '0000-0002-2499-8632': 39, '0000-0001

Total missing sample:  0
Text embedding shape:  (314, 50000)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (314, 50000)
Binary case
                     precision    recall  f1-score   support

0000-0001-5525-0494       0.99      0.96      0.97       156
0000-0003-2861-8286       0.96      0.99      0.97       158

           accuracy                           0.97       314
          macro avg       0.97      0.97      0.97       314
       weighted avg       0.97      0.97      0.97       314

TP:  156 TN:  149 FP:  7 FN:  2
MNB Accuracy:  0.9713375796178344
MNB F1:  0.9713233279551889
Binary case
                     precision    recall  f1-score   support

0000-0001-5525-0494       0.99      0.94      0.96       156
0000-0003-2861-8286       0.94      0.99      0.97       158

           accuracy                           0.96       314
          macro avg       0.97      0.96      0.96       314
       weighted avg       0.97

Multi-Class case
                     precision    recall  f1-score   support

0000-0001-5568-2916       1.00      0.89      0.94       105
0000-0001-9414-1653       1.00      0.87      0.93       104
0000-0002-9955-6003       0.95      1.00      0.97       487

           accuracy                           0.96       696
          macro avg       0.98      0.92      0.95       696
       weighted avg       0.96      0.96      0.96       696

[ 93   0  12   0  90  14   0   0 487]
[[ 93   0  12]
 [  0  90  14]
 [  0   0 487]]
TP:  [ 93  90 487] TN:  [591 592 183] FP:  [ 0  0 26] FN:  [12 14  0]
LR Accuracy:  0.9626436781609196
LR F1:  0.9470763303134437
Multi-Class case
                     precision    recall  f1-score   support

0000-0001-5568-2916       1.00      0.95      0.98       105
0000-0001-9414-1653       1.00      0.97      0.99       104
0000-0002-9955-6003       0.98      1.00      0.99       487

           accuracy                           0.99       696
          macro

w_chang  pass
For name:  a_murray
a_murray  pass
For name:  b_cao
b_cao  pass
For name:  k_sohn
k_sohn  pass
For name:  m_bennett
m_bennett  pass
For name:  a_sharma
a_sharma  pass
For name:  z_wei
z_wei  pass
For name:  x_gu
x_gu  pass
For name:  l_yang
l_yang  pass
For name:  h_hassan
h_hassan  pass
For name:  f_chen
f_chen  pass
For name:  g_rossi
g_rossi  pass
For name:  s_patil
s_patil  pass
For name:  m_kelly
m_kelly  pass
For name:  m_cheung
m_cheung  pass
For name:  j_weaver
j_weaver  pass
For name:  c_chien
c_chien  pass
For name:  s_yun
s_yun  pass
For name:  s_jung
s_jung  pass
For name:  e_gomes
e_gomes  pass
For name:  t_yamaguchi
t_yamaguchi  pass
For name:  p_oliveira
p_oliveira  pass
For name:  r_torres
r_torres  pass
For name:  a_esteves
a_esteves  pass
For name:  l_stevens
l_stevens  pass
For name:  a_chang
a_chang  pass
For name:  l_song
l_song  pass
For name:  j_delgado
j_delgado  pass
For name:  p_jensen
p_jensen  pass
For name:  t_allen
t_allen  pass
For name:  j_

Binary case
                     precision    recall  f1-score   support

0000-0001-9033-0158       0.99      1.00      0.99       194
0000-0002-1430-1360       1.00      0.98      0.99       101

           accuracy                           0.99       295
          macro avg       0.99      0.99      0.99       295
       weighted avg       0.99      0.99      0.99       295

TP:  99 TN:  194 FP:  0 FN:  2
LR Accuracy:  0.9932203389830508
LR F1:  0.9924358974358973
Binary case
                     precision    recall  f1-score   support

0000-0001-9033-0158       1.00      0.99      1.00       194
0000-0002-1430-1360       0.99      1.00      1.00       101

           accuracy                           1.00       295
          macro avg       1.00      1.00      1.00       295
       weighted avg       1.00      1.00      1.00       295

TP:  101 TN:  193 FP:  1 FN:  0
svc Accuracy:  0.9966101694915255
svc F1:  0.9962449561487252
For name:  r_ross
r_ross  pass
For name:  k_yamamoto


For name:  j_petersen
j_petersen  pass
For name:  k_shimizu
k_shimizu  pass
For name:  p_shaw
p_shaw  pass
For name:  g_coppola
g_coppola  pass
For name:  a_sinclair
a_sinclair  pass
For name:  y_pan
y_pan  pass
For name:  m_ramos
m_ramos  pass
For name:  j_tsai
j_tsai  pass
For name:  f_dai
f_dai  pass
For name:  t_martin
t_martin  pass
For name:  t_o'brien
t_o'brien  pass
For name:  s_may
s_may  pass
For name:  z_cai
z_cai  pass
For name:  a_pereira
a_pereira  pass
For name:  d_patel
d_patel  pass
For name:  a_james
a_james  pass
For name:  c_cao
c_cao  pass
For name:  c_brown
c_brown  pass
For name:  y_liang
y_liang  pass
For name:  y_fan
y_fan  pass
For name:  j_simon
j_simon  pass
For name:  m_jeong
m_jeong  pass
For name:  j_barrett
j_barrett  pass
For name:  d_elliott
d_elliott  pass
For name:  p_antunes
p_antunes  pass
For name:  x_yuan
x_yuan  pass
For name:  t_kim
t_kim  pass
For name:  a_cruz
a_cruz  pass
For name:  a_mora
a_mora  pass
For name:  j_walker
j_walker  pass
For 

Total missing sample:  0
Text embedding shape:  (470, 50000)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (470, 50000)
Multi-Class case
                     precision    recall  f1-score   support

0000-0003-1232-5307       0.97      0.93      0.95       124
0000-0003-1835-9436       0.93      1.00      0.97       200
0000-0003-3477-1172       1.00      0.95      0.97       146

           accuracy                           0.96       470
          macro avg       0.97      0.96      0.96       470
       weighted avg       0.97      0.96      0.96       470

[115   9   0   0 200   0   3   5 138]
[[115   9   0]
 [  0 200   0]
 [  3   5 138]]
TP:  [115 200 138] TN:  [343 256 324] FP:  [ 3 14  0] FN:  [9 0 8]
MNB Accuracy:  0.9638297872340426
MNB F1:  0.9628092613117386
Multi-Class case
                     precision    recall  f1-score   support

0000-0003-1232-5307       0.98      0.98      0.98       124
0000-0003-1835-9436     

s_antunes  pass
For name:  k_cho
k_cho  pass
For name:  j_sanderson
j_sanderson  pass
For name:  s_uddin
s_uddin  pass
For name:  a_batista
a_batista  pass
For name:  h_pereira
h_pereira  pass
For name:  a_patel
a_patel  pass
For name:  r_graham
r_graham  pass
For name:  a_nilsson
a_nilsson  pass
For name:  m_soto
m_soto  pass
For name:  g_guidi
g_guidi  pass
For name:  e_andersson
e_andersson  pass
For name:  s_reid
s_reid  pass
For name:  a_maleki
a_maleki  pass
For name:  j_moon
j_moon  pass
For name:  t_abe
t_abe  pass
For name:  x_fu
x_fu  pass
For name:  f_ortega
f_ortega  pass
For name:  r_morris
r_morris  pass
For name:  w_fang
w_fang  pass
For name:  m_amaral
m_amaral  pass
For name:  h_song
h_song  pass
For name:  h_dai
h_dai  pass
For name:  y_nakajima
y_nakajima  pass
For name:  t_warner
t_warner  pass
For name:  s_saha
s_saha  pass
For name:  j_fernandez
j_fernandez  pass
For name:  m_pan
m_pan  pass
For name:  a_simon
a_simon  pass
For name:  r_freitas
r_freitas  pass
For

Total missing sample:  0
Text embedding shape:  (398, 50000)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (398, 50000)
Binary case
                     precision    recall  f1-score   support

0000-0002-7751-1058       1.00      0.93      0.97       167
0000-0003-0960-6415       0.95      1.00      0.98       231

           accuracy                           0.97       398
          macro avg       0.98      0.97      0.97       398
       weighted avg       0.97      0.97      0.97       398

TP:  231 TN:  156 FP:  11 FN:  0
LR Accuracy:  0.9723618090452262
LR F1:  0.971344229246166
Binary case
                     precision    recall  f1-score   support

0000-0002-7751-1058       1.00      0.99      1.00       167
0000-0003-0960-6415       1.00      1.00      1.00       231

           accuracy                           1.00       398
          macro avg       1.00      1.00      1.00       398
       weighted avg       1.00  

s_das  pass
For name:  f_rodriguez
f_rodriguez  pass
For name:  w_peng
w_peng  pass
For name:  c_torres
c_torres  pass
For name:  s_rossi
s_rossi  pass
For name:  s_alavi
s_alavi  pass
For name:  r_marques
r_marques  pass
For name:  m_wheeler
m_wheeler  pass
For name:  l_rasmussen
l_rasmussen  pass
For name:  m_saad
m_saad  pass
For name:  j_carr
j_carr  pass
For name:  j_fraser
j_fraser  pass
For name:  s_woo
s_woo  pass
For name:  s_bartlett
s_bartlett  pass
For name:  m_lucas
m_lucas  pass
For name:  w_lee
Total sample size before apply threshold:  590
Counter({'0000-0003-3171-7672': 108, '0000-0001-5833-989X': 100, '0000-0003-3231-9764': 82, '0000-0002-1082-7592': 62, '0000-0003-3267-4811': 40, '0000-0001-7805-869X': 36, '0000-0003-2883-0391': 21, '0000-0002-0607-038X': 21, '0000-0002-5461-6770': 16, '0000-0002-3912-6095': 11, '0000-0001-6757-885X': 11, '0000-0001-6408-7668': 10, '0000-0002-9873-1033': 9, '0000-0001-7801-083X': 8, '0000-0001-8430-4797': 7, '0000-0002-2572-7287': 5,

Total missing sample:  0
Text embedding shape:  (292, 50000)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (292, 50000)
Binary case
                     precision    recall  f1-score   support

0000-0002-6391-1341       1.00      0.79      0.88       112
0000-0002-6794-6656       0.88      1.00      0.94       180

           accuracy                           0.92       292
          macro avg       0.94      0.89      0.91       292
       weighted avg       0.93      0.92      0.92       292

TP:  180 TN:  88 FP:  24 FN:  0
LR Accuracy:  0.9178082191780822
LR F1:  0.90875
Binary case
                     precision    recall  f1-score   support

0000-0002-6391-1341       1.00      0.93      0.96       112
0000-0002-6794-6656       0.96      1.00      0.98       180

           accuracy                           0.97       292
          macro avg       0.98      0.96      0.97       292
       weighted avg       0.97      0.97   

Total missing sample:  0
Text embedding shape:  (314, 50000)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (314, 50000)
Binary case
                     precision    recall  f1-score   support

0000-0001-5525-0494       0.99      0.92      0.96       156
0000-0003-2861-8286       0.93      0.99      0.96       158

           accuracy                           0.96       314
          macro avg       0.96      0.96      0.96       314
       weighted avg       0.96      0.96      0.96       314

TP:  157 TN:  144 FP:  12 FN:  1
LR Accuracy:  0.9585987261146497
LR F1:  0.9585276397736393
Binary case
                     precision    recall  f1-score   support

0000-0001-5525-0494       0.99      0.96      0.98       156
0000-0003-2861-8286       0.96      0.99      0.98       158

           accuracy                           0.98       314
          macro avg       0.98      0.98      0.98       314
       weighted avg       0.98 

c_franco  pass
For name:  v_wong
v_wong  pass
For name:  j_feng
j_feng  pass
For name:  s_murugesan
s_murugesan  pass
For name:  j_camacho
j_camacho  pass
For name:  b_moreno
b_moreno  pass
For name:  j_andersen
j_andersen  pass
For name:  j_bell
j_bell  pass
For name:  m_bull
m_bull  pass
For name:  s_gandhi
s_gandhi  pass
For name:  c_yang
c_yang  pass
For name:  s_paul
s_paul  pass
For name:  l_roberts
Total sample size before apply threshold:  363
Counter({'0000-0003-4270-253X': 206, '0000-0001-7885-8574': 120, '0000-0002-1455-5248': 18, '0000-0003-0085-9213': 14, '0000-0003-3892-2900': 3, '0000-0002-0329-8389': 2})
Total author before apply threshoid:  6
['0000-0003-4270-253X', '0000-0001-7885-8574']
Total author after apply threshoid:  2
Total sample size after apply threshold:  326
Total missing sample:  0
Text embedding shape:  (326, 50000)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (326, 50000)
Binary case
            

Total sample size before apply threshold:  658
Counter({'0000-0002-1940-6428': 219, '0000-0002-7074-8087': 194, '0000-0002-1674-443X': 56, '0000-0003-3327-828X': 42, '0000-0001-6587-7055': 33, '0000-0002-8811-9203': 29, '0000-0002-7509-1643': 22, '0000-0003-2045-9372': 13, '0000-0002-9161-7940': 11, '0000-0003-3712-1554': 10, '0000-0001-7672-9357': 6, '0000-0003-2113-0245': 5, '0000-0001-6847-7065': 5, '0000-0003-0977-3600': 4, '0000-0003-1372-4764': 2, '0000-0003-1734-7994': 2, '0000-0002-3269-1681': 2, '0000-0002-0183-0490': 1, '0000-0001-6646-050X': 1, '0000-0002-6646-951X': 1})
Total author before apply threshoid:  20
['0000-0002-1940-6428', '0000-0002-7074-8087']
Total author after apply threshoid:  2
Total sample size after apply threshold:  413
Total missing sample:  0
Text embedding shape:  (413, 50000)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (413, 50000)
Binary case
                     precision    recall  f1-score

h_young  pass
For name:  a_vincent
a_vincent  pass
For name:  a_monteiro
a_monteiro  pass
For name:  d_park
d_park  pass
For name:  d_gao
d_gao  pass
For name:  d_quinn
d_quinn  pass
For name:  n_dias
n_dias  pass
For name:  k_fisher
k_fisher  pass
For name:  m_schubert
m_schubert  pass
For name:  j_peters
j_peters  pass
For name:  e_zimmermann
e_zimmermann  pass
For name:  c_zhang
c_zhang  pass
For name:  h_shin
h_shin  pass
For name:  r_reis
Total sample size before apply threshold:  615
Counter({'0000-0002-4295-6129': 423, '0000-0002-9639-7940': 113, '0000-0002-9872-9865': 27, '0000-0001-9689-4085': 21, '0000-0002-0681-4721': 10, '0000-0003-0328-1840': 7, '0000-0003-0937-8045': 7, '0000-0003-3746-6894': 4, '0000-0002-6618-2412': 2, '0000-0002-6935-3459': 1})
Total author before apply threshoid:  10
['0000-0002-9639-7940', '0000-0002-4295-6129']
Total author after apply threshoid:  2
Total sample size after apply threshold:  536
Total missing sample:  0
Text embedding shape:  (536, 5

Total missing sample:  0
Text embedding shape:  (470, 50000)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (470, 50000)
Multi-Class case
                     precision    recall  f1-score   support

0000-0003-1232-5307       0.98      0.98      0.98       124
0000-0003-1835-9436       1.00      1.00      1.00       200
0000-0003-3477-1172       0.99      0.99      0.99       146

           accuracy                           0.99       470
          macro avg       0.99      0.99      0.99       470
       weighted avg       0.99      0.99      0.99       470

[122   1   1   0 200   0   2   0 144]
[[122   1   1]
 [  0 200   0]
 [  2   0 144]]
TP:  [122 200 144] TN:  [344 269 323] FP:  [2 1 1] FN:  [2 0 2]
LR Accuracy:  0.9914893617021276
LR F1:  0.990355974601795
Multi-Class case
                     precision    recall  f1-score   support

0000-0003-1232-5307       0.97      0.99      0.98       124
0000-0003-1835-9436       1.00

For name:  t_abe
t_abe  pass
For name:  x_fu
x_fu  pass
For name:  f_ortega
f_ortega  pass
For name:  r_morris
r_morris  pass
For name:  w_fang
w_fang  pass
For name:  m_amaral
m_amaral  pass
For name:  h_song
h_song  pass
For name:  h_dai
h_dai  pass
For name:  y_nakajima
y_nakajima  pass
For name:  t_warner
t_warner  pass
For name:  s_saha
s_saha  pass
For name:  j_fernandez
j_fernandez  pass
For name:  m_pan
m_pan  pass
For name:  a_simon
a_simon  pass
For name:  r_freitas
r_freitas  pass
For name:  c_yun
c_yun  pass
For name:  j_huang
j_huang  pass
For name:  p_santos
p_santos  pass
For name:  n_young
n_young  pass
For name:  d_ross
d_ross  pass
For name:  q_wang
q_wang  pass
For name:  c_cardoso
c_cardoso  pass
For name:  j_matthews
j_matthews  pass
For name:  g_lee
g_lee  pass
For name:  m_salem
m_salem  pass
For name:  h_lai
h_lai  pass
For name:  r_harris
r_harris  pass
For name:  c_vaughan
c_vaughan  pass
For name:  e_thompson
e_thompson  pass
For name:  r_gomes
r_gomes  pass


Binary case
                     precision    recall  f1-score   support

0000-0002-7751-1058       1.00      0.94      0.97       167
0000-0003-0960-6415       0.96      1.00      0.98       231

           accuracy                           0.97       398
          macro avg       0.98      0.97      0.97       398
       weighted avg       0.98      0.97      0.97       398

TP:  231 TN:  157 FP:  10 FN:  0
LR Accuracy:  0.9748743718592965
LR F1:  0.9739746808955848
Binary case
                     precision    recall  f1-score   support

0000-0002-7751-1058       0.99      0.94      0.97       167
0000-0003-0960-6415       0.96      1.00      0.98       231

           accuracy                           0.97       398
          macro avg       0.98      0.97      0.97       398
       weighted avg       0.97      0.97      0.97       398

TP:  230 TN:  157 FP:  10 FN:  1
svc Accuracy:  0.9723618090452262
svc F1:  0.9713996406990038
For name:  j_moraes
j_moraes  pass
For name:  e_mo

j_carr  pass
For name:  j_fraser
j_fraser  pass
For name:  s_woo
s_woo  pass
For name:  s_bartlett
s_bartlett  pass
For name:  m_lucas
m_lucas  pass
For name:  w_lee
Total sample size before apply threshold:  590
Counter({'0000-0003-3171-7672': 108, '0000-0001-5833-989X': 100, '0000-0003-3231-9764': 82, '0000-0002-1082-7592': 62, '0000-0003-3267-4811': 40, '0000-0001-7805-869X': 36, '0000-0003-2883-0391': 21, '0000-0002-0607-038X': 21, '0000-0002-5461-6770': 16, '0000-0002-3912-6095': 11, '0000-0001-6757-885X': 11, '0000-0001-6408-7668': 10, '0000-0002-9873-1033': 9, '0000-0001-7801-083X': 8, '0000-0001-8430-4797': 7, '0000-0002-2572-7287': 5, '0000-0002-6766-8481': 5, '0000-0001-8706-6026': 4, '0000-0002-0036-2859': 4, '0000-0002-9624-0505': 3, '0000-0002-3413-4029': 3, '0000-0003-1817-8395': 3, '0000-0003-1744-8525': 3, '0000-0001-8052-2420': 2, '0000-0003-0853-8561': 2, '0000-0001-7285-4054': 2, '0000-0001-9645-8179': 2, '0000-0002-4383-756X': 2, '0000-0003-1911-3454': 2, '0000-0003

TP:  180 TN:  87 FP:  25 FN:  0
LR Accuracy:  0.9143835616438356
LR F1:  0.9047183971807087
Binary case
                     precision    recall  f1-score   support

0000-0002-6391-1341       1.00      0.86      0.92       112
0000-0002-6794-6656       0.92      1.00      0.96       180

           accuracy                           0.95       292
          macro avg       0.96      0.93      0.94       292
       weighted avg       0.95      0.95      0.94       292

TP:  180 TN:  96 FP:  16 FN:  0
svc Accuracy:  0.9452054794520548
svc F1:  0.9402618657937807
For name:  r_sinha
r_sinha  pass
For name:  c_turner
c_turner  pass
For name:  y_su
y_su  pass
For name:  a_popov
a_popov  pass
For name:  w_liao
w_liao  pass
For name:  j_zhong
j_zhong  pass
For name:  a_wheeler
a_wheeler  pass
For name:  m_walsh
m_walsh  pass
For name:  r_figueiredo
r_figueiredo  pass
For name:  y_lin
Total sample size before apply threshold:  785
Counter({'0000-0003-3791-7587': 146, '0000-0001-8153-1441': 115,

                     precision    recall  f1-score   support

0000-0001-5525-0494       0.99      0.88      0.94       156
0000-0003-2861-8286       0.90      0.99      0.94       158

           accuracy                           0.94       314
          macro avg       0.94      0.94      0.94       314
       weighted avg       0.94      0.94      0.94       314

TP:  157 TN:  138 FP:  18 FN:  1
svc Accuracy:  0.9394904458598726
svc F1:  0.939268081640963
For name:  m_guerra
m_guerra  pass
For name:  h_suzuki
h_suzuki  pass
For name:  m_cohen
m_cohen  pass
For name:  m_kobayashi
m_kobayashi  pass
For name:  s_wright
s_wright  pass
For name:  a_mills
a_mills  pass
For name:  c_west
c_west  pass
For name:  a_marino
a_marino  pass
For name:  r_jiang
r_jiang  pass
For name:  t_becker
t_becker  pass
For name:  s_pedersen
s_pedersen  pass
For name:  a_ali
a_ali  pass
For name:  k_jones
k_jones  pass
For name:  m_becker
m_becker  pass
For name:  c_marshall
c_marshall  pass
For name:  s_raf

s_paul  pass
For name:  l_roberts
Total sample size before apply threshold:  363
Counter({'0000-0003-4270-253X': 206, '0000-0001-7885-8574': 120, '0000-0002-1455-5248': 18, '0000-0003-0085-9213': 14, '0000-0003-3892-2900': 3, '0000-0002-0329-8389': 2})
Total author before apply threshoid:  6
['0000-0003-4270-253X', '0000-0001-7885-8574']
Total author after apply threshoid:  2
Total sample size after apply threshold:  326
Total missing sample:  0
Text embedding shape:  (326, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (326, 100)
Binary case
                     precision    recall  f1-score   support

0000-0001-7885-8574       1.00      0.76      0.86       120
0000-0003-4270-253X       0.88      1.00      0.93       206

           accuracy                           0.91       326
          macro avg       0.94      0.88      0.90       326
       weighted avg       0.92      0.91      0.91       326

TP:  206 TN:  91 FP:  

Total missing sample:  0
Text embedding shape:  (413, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (413, 100)
Binary case
                     precision    recall  f1-score   support

0000-0002-1940-6428       0.91      0.97      0.94       219
0000-0002-7074-8087       0.96      0.89      0.93       194

           accuracy                           0.93       413
          macro avg       0.94      0.93      0.93       413
       weighted avg       0.93      0.93      0.93       413

TP:  173 TN:  212 FP:  7 FN:  21
LR Accuracy:  0.9322033898305084
LR F1:  0.9315933935923525
Binary case
                     precision    recall  f1-score   support

0000-0002-1940-6428       0.93      0.97      0.95       219
0000-0002-7074-8087       0.96      0.92      0.94       194

           accuracy                           0.94       413
          macro avg       0.95      0.94      0.94       413
       weighted avg       0.95     

m_schubert  pass
For name:  j_peters
j_peters  pass
For name:  e_zimmermann
e_zimmermann  pass
For name:  c_zhang
c_zhang  pass
For name:  h_shin
h_shin  pass
For name:  r_reis
Total sample size before apply threshold:  615
Counter({'0000-0002-4295-6129': 423, '0000-0002-9639-7940': 113, '0000-0002-9872-9865': 27, '0000-0001-9689-4085': 21, '0000-0002-0681-4721': 10, '0000-0003-0328-1840': 7, '0000-0003-0937-8045': 7, '0000-0003-3746-6894': 4, '0000-0002-6618-2412': 2, '0000-0002-6935-3459': 1})
Total author before apply threshoid:  10
['0000-0002-9639-7940', '0000-0002-4295-6129']
Total author after apply threshoid:  2
Total sample size after apply threshold:  536
Total missing sample:  0
Text embedding shape:  (536, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (536, 100)
Binary case
                     precision    recall  f1-score   support

0000-0002-4295-6129       0.93      1.00      0.96       423
0000-0002-9639-7940

Total missing sample:  0
Text embedding shape:  (470, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (470, 100)
Multi-Class case
                     precision    recall  f1-score   support

0000-0003-1232-5307       0.97      0.95      0.96       124
0000-0003-1835-9436       0.99      0.99      0.99       200
0000-0003-3477-1172       0.96      0.98      0.97       146

           accuracy                           0.98       470
          macro avg       0.97      0.97      0.97       470
       weighted avg       0.98      0.98      0.98       470

[118   1   5   1 198   1   3   0 143]
[[118   1   5]
 [  1 198   1]
 [  3   0 143]]
TP:  [118 198 143] TN:  [342 269 318] FP:  [4 1 6] FN:  [6 2 3]
LR Accuracy:  0.9765957446808511
LR F1:  0.9737741073090609
Multi-Class case
                     precision    recall  f1-score   support

0000-0003-1232-5307       0.95      0.98      0.97       124
0000-0003-1835-9436       0.99   

c_yun  pass
For name:  j_huang
j_huang  pass
For name:  p_santos
p_santos  pass
For name:  n_young
n_young  pass
For name:  d_ross
d_ross  pass
For name:  q_wang
q_wang  pass
For name:  c_cardoso
c_cardoso  pass
For name:  j_matthews
j_matthews  pass
For name:  g_lee
g_lee  pass
For name:  m_salem
m_salem  pass
For name:  h_lai
h_lai  pass
For name:  r_harris
r_harris  pass
For name:  c_vaughan
c_vaughan  pass
For name:  e_thompson
e_thompson  pass
For name:  r_gomes
r_gomes  pass
For name:  r_bennett
r_bennett  pass
For name:  m_collins
m_collins  pass
For name:  m_cowley
m_cowley  pass
For name:  p_teixeira
p_teixeira  pass
For name:  c_cox
c_cox  pass
For name:  s_hsu
s_hsu  pass
For name:  f_williams
f_williams  pass
For name:  d_parsons
d_parsons  pass
For name:  a_choudhury
a_choudhury  pass
For name:  c_richter
c_richter  pass
For name:  m_hossain
m_hossain  pass
For name:  v_alves
v_alves  pass
For name:  j_becker
j_becker  pass
For name:  m_soares
m_soares  pass
For name:  j_y

Binary case
                     precision    recall  f1-score   support

0000-0002-7751-1058       0.99      0.96      0.98       167
0000-0003-0960-6415       0.97      0.99      0.98       231

           accuracy                           0.98       398
          macro avg       0.98      0.98      0.98       398
       weighted avg       0.98      0.98      0.98       398

TP:  229 TN:  161 FP:  6 FN:  2
svc Accuracy:  0.9798994974874372
svc F1:  0.9792950968916634
For name:  j_moraes
j_moraes  pass
For name:  e_moreno
e_moreno  pass
For name:  r_little
r_little  pass
For name:  t_kobayashi
t_kobayashi  pass
For name:  a_lin
a_lin  pass
For name:  a_miranda
a_miranda  pass
For name:  h_vogel
h_vogel  pass
For name:  m_campos
m_campos  pass
For name:  d_stewart
d_stewart  pass
For name:  j_abrantes
j_abrantes  pass
For name:  j_arroyo
j_arroyo  pass
For name:  a_giuliani
a_giuliani  pass
For name:  f_campos
f_campos  pass
For name:  a_mitchell
a_mitchell  pass
For name:  c_murray
c

Total missing sample:  0
Text embedding shape:  (208, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (208, 100)
Binary case
                     precision    recall  f1-score   support

0000-0001-5833-989X       0.96      0.93      0.94       100
0000-0003-3171-7672       0.94      0.96      0.95       108

           accuracy                           0.95       208
          macro avg       0.95      0.95      0.95       208
       weighted avg       0.95      0.95      0.95       208

TP:  104 TN:  93 FP:  7 FN:  4
LR Accuracy:  0.9471153846153846
LR F1:  0.9469670630229701
Binary case
                     precision    recall  f1-score   support

0000-0001-5833-989X       0.92      0.91      0.91       100
0000-0003-3171-7672       0.92      0.93      0.92       108

           accuracy                           0.92       208
          macro avg       0.92      0.92      0.92       208
       weighted avg       0.92      0

Total missing sample:  0
Text embedding shape:  (261, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (261, 100)
Binary case
                     precision    recall  f1-score   support

0000-0001-8153-1441       0.99      0.94      0.96       115
0000-0003-3791-7587       0.95      0.99      0.97       146

           accuracy                           0.97       261
          macro avg       0.97      0.97      0.97       261
       weighted avg       0.97      0.97      0.97       261

TP:  145 TN:  108 FP:  7 FN:  1
LR Accuracy:  0.9693486590038314
LR F1:  0.9687200383509108
Binary case
                     precision    recall  f1-score   support

0000-0001-8153-1441       0.98      0.91      0.95       115
0000-0003-3791-7587       0.94      0.99      0.96       146

           accuracy                           0.95       261
          macro avg       0.96      0.95      0.95       261
       weighted avg       0.96      

Binary case
                     precision    recall  f1-score   support

0000-0002-2002-4339       0.96      0.98      0.97       175
0000-0003-3470-923X       0.98      0.96      0.97       185

           accuracy                           0.97       360
          macro avg       0.97      0.97      0.97       360
       weighted avg       0.97      0.97      0.97       360

TP:  178 TN:  172 FP:  3 FN:  7
svc Accuracy:  0.9722222222222222
svc F1:  0.972214504028897
For name:  c_rodriguez
c_rodriguez  pass
For name:  p_hall
p_hall  pass
For name:  r_srivastava
r_srivastava  pass
For name:  a_macedo
a_macedo  pass
For name:  m_schultz
m_schultz  pass
For name:  s_jacobs
s_jacobs  pass
For name:  c_hong
c_hong  pass
For name:  r_mohan
r_mohan  pass
For name:  r_hill
r_hill  pass
For name:  q_shen
q_shen  pass
For name:  l_schmidt
l_schmidt  pass
For name:  s_qin
s_qin  pass
For name:  a_fabbri
a_fabbri  pass
For name:  l_robinson
l_robinson  pass
For name:  r_gross
r_gross  pass
For n

o_ahmed  pass
For name:  t_shimada
t_shimada  pass
For name:  a_watts
a_watts  pass
For name:  b_oliveira
b_oliveira  pass
For name:  t_ito
t_ito  pass
For name:  t_jackson
t_jackson  pass
For name:  m_romero
m_romero  pass
For name:  j_west
j_west  pass
For name:  c_guo
c_guo  pass
For name:  m_hansen
m_hansen  pass
For name:  x_qian
x_qian  pass
For name:  m_wagner
m_wagner  pass
For name:  d_campos
d_campos  pass
For name:  r_clark
r_clark  pass
For name:  b_zhou
b_zhou  pass
For name:  x_yan
x_yan  pass
For name:  x_li
x_li  pass
For name:  j_burton
j_burton  pass
For name:  x_feng
x_feng  pass
For name:  w_hussein
w_hussein  pass
For name:  c_santos
c_santos  pass
For name:  j_figueroa
j_figueroa  pass
For name:  w_cui
w_cui  pass
For name:  d_moreira
d_moreira  pass
For name:  m_graham
m_graham  pass
For name:  g_dias
g_dias  pass
For name:  h_yoshida
h_yoshida  pass
For name:  m_branco
m_branco  pass
For name:  k_chong
k_chong  pass
For name:  j_kumar
j_kumar  pass
For name:  a_

Total missing sample:  0
Text embedding shape:  (295, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (295, 100)
Binary case
                     precision    recall  f1-score   support

0000-0001-9033-0158       0.97      0.97      0.97       194
0000-0002-1430-1360       0.94      0.95      0.95       101

           accuracy                           0.96       295
          macro avg       0.96      0.96      0.96       295
       weighted avg       0.96      0.96      0.96       295

TP:  96 TN:  188 FP:  6 FN:  5
LR Accuracy:  0.9627118644067797
LR F1:  0.9586945176359771
Binary case
                     precision    recall  f1-score   support

0000-0001-9033-0158       0.93      0.96      0.95       194
0000-0002-1430-1360       0.93      0.86      0.89       101

           accuracy                           0.93       295
          macro avg       0.93      0.91      0.92       295
       weighted avg       0.93      0

For name:  j_alves
j_alves  pass
For name:  j_seo
j_seo  pass
For name:  y_tang
y_tang  pass
For name:  a_norman
a_norman  pass
For name:  s_tanaka
s_tanaka  pass
For name:  c_wen
c_wen  pass
For name:  c_myers
c_myers  pass
For name:  v_santos
v_santos  pass
For name:  j_brown
j_brown  pass
For name:  b_pandey
b_pandey  pass
For name:  d_morgan
d_morgan  pass
For name:  r_smith
r_smith  pass
For name:  a_guerrero
a_guerrero  pass
For name:  a_grant
a_grant  pass
For name:  v_kumar
v_kumar  pass
For name:  p_shah
p_shah  pass
For name:  t_yu
t_yu  pass
For name:  r_singh
r_singh  pass
For name:  c_baker
c_baker  pass
For name:  a_cattaneo
a_cattaneo  pass
For name:  a_ferrari
a_ferrari  pass
For name:  a_murphy
a_murphy  pass
For name:  f_hong
f_hong  pass
For name:  m_ferrari
m_ferrari  pass
For name:  j_paredes
j_paredes  pass
For name:  z_zhao
z_zhao  pass
For name:  j_cao
j_cao  pass
For name:  d_kuo
d_kuo  pass
For name:  a_andersen
a_andersen  pass
For name:  m_longo
m_longo  pas

Multi-Class case
                     precision    recall  f1-score   support

0000-0003-1232-5307       0.98      0.92      0.95       124
0000-0003-1835-9436       0.96      0.97      0.97       200
0000-0003-3477-1172       0.95      0.98      0.97       146

           accuracy                           0.96       470
          macro avg       0.96      0.96      0.96       470
       weighted avg       0.96      0.96      0.96       470

[114   7   3   1 195   4   1   2 143]
[[114   7   3]
 [  1 195   4]
 [  1   2 143]]
TP:  [114 195 143] TN:  [344 261 317] FP:  [2 9 7] FN:  [10  5  3]
LR Accuracy:  0.9617021276595744
LR F1:  0.9605209169565606
Multi-Class case
                     precision    recall  f1-score   support

0000-0003-1232-5307       0.96      0.88      0.92       124
0000-0003-1835-9436       0.93      0.93      0.93       200
0000-0003-3477-1172       0.89      0.96      0.92       146

           accuracy                           0.93       470
          macro av

f_ortega  pass
For name:  r_morris
r_morris  pass
For name:  w_fang
w_fang  pass
For name:  m_amaral
m_amaral  pass
For name:  h_song
h_song  pass
For name:  h_dai
h_dai  pass
For name:  y_nakajima
y_nakajima  pass
For name:  t_warner
t_warner  pass
For name:  s_saha
s_saha  pass
For name:  j_fernandez
j_fernandez  pass
For name:  m_pan
m_pan  pass
For name:  a_simon
a_simon  pass
For name:  r_freitas
r_freitas  pass
For name:  c_yun
c_yun  pass
For name:  j_huang
j_huang  pass
For name:  p_santos
p_santos  pass
For name:  n_young
n_young  pass
For name:  d_ross
d_ross  pass
For name:  q_wang
q_wang  pass
For name:  c_cardoso
c_cardoso  pass
For name:  j_matthews
j_matthews  pass
For name:  g_lee
g_lee  pass
For name:  m_salem
m_salem  pass
For name:  h_lai
h_lai  pass
For name:  r_harris
r_harris  pass
For name:  c_vaughan
c_vaughan  pass
For name:  e_thompson
e_thompson  pass
For name:  r_gomes
r_gomes  pass
For name:  r_bennett
r_bennett  pass
For name:  m_collins
m_collins  pass
Fo

Binary case
                     precision    recall  f1-score   support

0000-0002-7751-1058       0.99      0.98      0.99       167
0000-0003-0960-6415       0.99      1.00      0.99       231

           accuracy                           0.99       398
          macro avg       0.99      0.99      0.99       398
       weighted avg       0.99      0.99      0.99       398

TP:  230 TN:  164 FP:  3 FN:  1
LR Accuracy:  0.9899497487437185
LR F1:  0.9896655587868717
Binary case
                     precision    recall  f1-score   support

0000-0002-7751-1058       0.99      0.98      0.99       167
0000-0003-0960-6415       0.99      1.00      0.99       231

           accuracy                           0.99       398
          macro avg       0.99      0.99      0.99       398
       weighted avg       0.99      0.99      0.99       398

TP:  230 TN:  164 FP:  3 FN:  1
svc Accuracy:  0.9899497487437185
svc F1:  0.9896655587868717
For name:  j_moraes
j_moraes  pass
For name:  e_more

c_torres  pass
For name:  s_rossi
s_rossi  pass
For name:  s_alavi
s_alavi  pass
For name:  r_marques
r_marques  pass
For name:  m_wheeler
m_wheeler  pass
For name:  l_rasmussen
l_rasmussen  pass
For name:  m_saad
m_saad  pass
For name:  j_carr
j_carr  pass
For name:  j_fraser
j_fraser  pass
For name:  s_woo
s_woo  pass
For name:  s_bartlett
s_bartlett  pass
For name:  m_lucas
m_lucas  pass
For name:  w_lee
Total sample size before apply threshold:  590
Counter({'0000-0003-3171-7672': 108, '0000-0001-5833-989X': 100, '0000-0003-3231-9764': 82, '0000-0002-1082-7592': 62, '0000-0003-3267-4811': 40, '0000-0001-7805-869X': 36, '0000-0003-2883-0391': 21, '0000-0002-0607-038X': 21, '0000-0002-5461-6770': 16, '0000-0002-3912-6095': 11, '0000-0001-6757-885X': 11, '0000-0001-6408-7668': 10, '0000-0002-9873-1033': 9, '0000-0001-7801-083X': 8, '0000-0001-8430-4797': 7, '0000-0002-2572-7287': 5, '0000-0002-6766-8481': 5, '0000-0001-8706-6026': 4, '0000-0002-0036-2859': 4, '0000-0002-9624-0505': 3,

Total missing sample:  0
Text embedding shape:  (292, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (292, 100)
Binary case
                     precision    recall  f1-score   support

0000-0002-6391-1341       0.99      0.98      0.99       112
0000-0002-6794-6656       0.99      0.99      0.99       180

           accuracy                           0.99       292
          macro avg       0.99      0.99      0.99       292
       weighted avg       0.99      0.99      0.99       292

TP:  179 TN:  110 FP:  2 FN:  1
LR Accuracy:  0.9897260273972602
LR F1:  0.9891184179471573
Binary case
                     precision    recall  f1-score   support

0000-0002-6391-1341       0.97      0.96      0.97       112
0000-0002-6794-6656       0.98      0.98      0.98       180

           accuracy                           0.98       292
          macro avg       0.98      0.97      0.97       292
       weighted avg       0.98      

Total missing sample:  0
Text embedding shape:  (314, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (314, 100)
Binary case
                     precision    recall  f1-score   support

0000-0001-5525-0494       0.99      0.99      0.99       156
0000-0003-2861-8286       0.99      0.99      0.99       158

           accuracy                           0.99       314
          macro avg       0.99      0.99      0.99       314
       weighted avg       0.99      0.99      0.99       314

TP:  156 TN:  154 FP:  2 FN:  2
LR Accuracy:  0.9872611464968153
LR F1:  0.987260629665693
Binary case
                     precision    recall  f1-score   support

0000-0001-5525-0494       0.98      0.98      0.98       156
0000-0003-2861-8286       0.98      0.98      0.98       158

           accuracy                           0.98       314
          macro avg       0.98      0.98      0.98       314
       weighted avg       0.98      0

c_yang  pass
For name:  s_paul
s_paul  pass
For name:  l_roberts
Total sample size before apply threshold:  363
Counter({'0000-0003-4270-253X': 206, '0000-0001-7885-8574': 120, '0000-0002-1455-5248': 18, '0000-0003-0085-9213': 14, '0000-0003-3892-2900': 3, '0000-0002-0329-8389': 2})
Total author before apply threshoid:  6
['0000-0003-4270-253X', '0000-0001-7885-8574']
Total author after apply threshoid:  2
Total sample size after apply threshold:  326
Total missing sample:  0
Text embedding shape:  (326, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (326, 100)
Binary case
                     precision    recall  f1-score   support

0000-0001-7885-8574       1.00      0.95      0.97       120
0000-0003-4270-253X       0.97      1.00      0.99       206

           accuracy                           0.98       326
          macro avg       0.99      0.97      0.98       326
       weighted avg       0.98      0.98      0.98   

Total missing sample:  0
Text embedding shape:  (413, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (413, 100)
Binary case
                     precision    recall  f1-score   support

0000-0002-1940-6428       0.97      0.98      0.98       219
0000-0002-7074-8087       0.98      0.96      0.97       194

           accuracy                           0.97       413
          macro avg       0.97      0.97      0.97       413
       weighted avg       0.97      0.97      0.97       413

TP:  187 TN:  215 FP:  4 FN:  7
LR Accuracy:  0.9733656174334141
LR F1:  0.9732426303854875
Binary case
                     precision    recall  f1-score   support

0000-0002-1940-6428       0.96      0.97      0.97       219
0000-0002-7074-8087       0.97      0.95      0.96       194

           accuracy                           0.96       413
          macro avg       0.96      0.96      0.96       413
       weighted avg       0.96      

Total missing sample:  0
Text embedding shape:  (536, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (536, 100)
Binary case
                     precision    recall  f1-score   support

0000-0002-4295-6129       0.99      1.00      0.99       423
0000-0002-9639-7940       0.98      0.97      0.98       113

           accuracy                           0.99       536
          macro avg       0.99      0.98      0.99       536
       weighted avg       0.99      0.99      0.99       536

TP:  110 TN:  421 FP:  2 FN:  3
LR Accuracy:  0.9906716417910447
LR F1:  0.9859372950282042
Binary case
                     precision    recall  f1-score   support

0000-0002-4295-6129       0.99      0.99      0.99       423
0000-0002-9639-7940       0.97      0.96      0.97       113

           accuracy                           0.99       536
          macro avg       0.98      0.98      0.98       536
       weighted avg       0.99      

Total missing sample:  0
Text embedding shape:  (470, 100)
Total missing sample:  0
Citation embedding shape:  (0, 0)
Final feature (combined embedding) shape:  (470, 100)
Multi-Class case
                     precision    recall  f1-score   support

0000-0003-1232-5307       0.98      0.98      0.98       124
0000-0003-1835-9436       1.00      1.00      1.00       200
0000-0003-3477-1172       0.99      0.99      0.99       146

           accuracy                           0.99       470
          macro avg       0.99      0.99      0.99       470
       weighted avg       0.99      0.99      0.99       470

[122   0   2   0 200   0   2   0 144]
[[122   0   2]
 [  0 200   0]
 [  2   0 144]]
TP:  [122 200 144] TN:  [344 270 322] FP:  [2 0 2] FN:  [2 0 2]
LR Accuracy:  0.9914893617021276
LR F1:  0.9900574458683163
Multi-Class case
                     precision    recall  f1-score   support

0000-0003-1232-5307       0.95      0.98      0.96       124
0000-0003-1835-9436       1.00   

In [ ]:
print(pp_text_emb)
print(lr_diff_embedding_result)
print(svm_diff_embedding_result)

In [ ]:
# combine n2v with textual embedding result together


In [ ]:
# accuracy
from statistics import mean 
cleaned_svcLinear_accuracy = [x for x in all_svcLinear_accuracy if isinstance(x, float)]
cleaned_lr_accuracy = [x for x in all_LR_accuracy if isinstance(x, float)]
print(len(cleaned_svcLinear_accuracy))
print(len(cleaned_lr_accuracy))
print(mean(cleaned_svcLinear_accuracy))
print(mean(cleaned_lr_accuracy))

In [ ]:
# f1
from statistics import mean 
# remove string from result
cleaned_svcLinear_f1 = [x for x in all_svcLinear_f1 if isinstance(x, float)]
cleaned_lr_f1 = [x for x in all_LR_f1 if isinstance(x, float)]
print(len(cleaned_svcLinear_f1))
print(len(cleaned_lr_f1))
print(mean(cleaned_svcLinear_f1))
print(mean(cleaned_lr_f1))

In [ ]:
%reset

In [ ]:
%who